name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: model_service
  REGISTRY: ghcr.io
  USERNAME: ${{ github.repository_owner }}
  RAW_TAG: ${{ github.ref }}
  TAG: $(echo "${RAW_TAG}" | sed 's@refs/heads/@@')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        env:
            API_KEY: ${{ secrets.API_KEY }}
            APP_NAME: ${{ vars.APP_NAME }}

