name: Build and Publish Docker Image

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: model_service
  REGISTRY: ghcr.io
  USERNAME: ${{ github.repository_owner }}
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Registry Login (ghcr.io)
        run: |
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        env:
            API_KEY: ${{ secrets.API_KEY }}
            APP_NAME: ${{ vars.APP_NAME }}

